// <auto-generated />
using Day1Task1.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day1Task1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Day1Task1.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Isaac Asimov"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Agatha Christie"
                        });
                });

            modelBuilder.Entity("Day1Task1.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Isbn = "",
                            PageCount = 310,
                            Title = "The Hobbit",
                            Year = 1937
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Isbn = "",
                            PageCount = 423,
                            Title = "The Fellowship of the Ring",
                            Year = 1954
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Isbn = "",
                            PageCount = 352,
                            Title = "The Two Towers",
                            Year = 1954
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Isbn = "",
                            PageCount = 255,
                            Title = "Foundation",
                            Year = 1951
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            Isbn = "",
                            PageCount = 224,
                            Title = "I, Robot",
                            Year = 1950
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            Isbn = "",
                            PageCount = 206,
                            Title = "The Caves of Steel",
                            Year = 1954
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            Isbn = "",
                            PageCount = 256,
                            Title = "Murder on the Orient Express",
                            Year = 1934
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            Isbn = "",
                            PageCount = 272,
                            Title = "And Then There Were None",
                            Year = 1939
                        });
                });

            modelBuilder.Entity("Day1Task1.Models.BookTag", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("BookTags");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            TagId = 1
                        },
                        new
                        {
                            BookId = 2,
                            TagId = 1
                        },
                        new
                        {
                            BookId = 1,
                            TagId = 4
                        },
                        new
                        {
                            BookId = 4,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 5,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 7,
                            TagId = 3
                        });
                });

            modelBuilder.Entity("Day1Task1.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Classic"
                        });
                });

            modelBuilder.Entity("Day1Task1.Models.Book", b =>
                {
                    b.HasOne("Day1Task1.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Day1Task1.Models.BookTag", b =>
                {
                    b.HasOne("Day1Task1.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Day1Task1.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Day1Task1.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
